#!/bin/bash
#
# Author: Jordan Doyle.
#

# shellcheck source=../log.sh
source log.sh
# shellcheck source=../setting.sh
source setting.sh
# shellcheck source=../util.sh
source util.sh

# shellcheck disable=SC2317  # Ignore unreachable commands warning
function exit_cleanup() {
    code=$?
    [[ -d "$target" ]] && rm -r "$target"
    log_execution_time
    exit $((code))
}

target="target"
trap exit_cleanup EXIT

usage="Usage: $(basename "$0") [-h] -o DIR -a FILE"
while getopts ':ho:a:' option; do
    case "$option" in
        h) 
            info "$usage" 
            exit
            ;;
        e)
            events="$OPTARG"
            ;;
        o)
            output="$OPTARG"
            ;;
        a)
            apk="$OPTARG"
            ;;
        :) 
            error "Missing argument for -$OPTARG"
            error "$usage"
            exit 1
            ;;
        ?)
            error "Illegal option: -$OPTARG"
            error "$usage"
            exit 1
            ;;
    esac
done

if [[ ! "$output" ]] || [[ ! "$apk" ]]; then
    error "Arguments -o and -a must be provided."
    error "$usage"
    exit 1
fi

check_output_exists
output=$(readlink -f "$output")

check_apk_exists
app_name=$(basename "$apk" .apk)
app_title=$(format_app_title "$app_name")
get_input_apk input_apk "$apk"

if [[ -z $results_dir_name ]] || [[ -z "$events" ]]; then
    error "Default settings have not been provided."
    exit 2
fi

if [[ -z $task ]]; then
    warn "No task name provided, using 'traversal'."
    task="traversal"
fi

jar="traversal.jar"
if [[ ! -f $jar ]]; then
    error "Jar file does not exist."
    exit 3
fi

results="$output/$results_dir_name/$app_name/$task"
launch_emulator "api28_0" "$results/emulator_$test.log"
adb logcat -c

timeout="1h"
info "Traversing $app_title."
timeout $timeout java -Xms4g -jar $jar -a "${input_apk:?}" -o "$results" \
    -m 150 -t "DFS" 2>&1 | prepend
code=${PIPESTATUS[0]}

if [[ $code -eq 124 ]]; then
    error "Traversal timed out on $app_title (>$timeout)."
    exit $((code))
elif [[ $code -ne 0 ]]; then
    error "Traversing $app_title failed (Err: $code)."
    exit $((code))
fi

[[ -d $target ]] && mv $target "$results"
adb logcat -d > "$results/logcat_$test.log"
adb logcat -c
info "Task completed successfully."
